version: '3'

services:
  bot:
    pull_policy: build
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: $BOT_TOKEN
      TEST_GUILDS: $TEST_GUILDS